# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

def testpods
  pod 'Quick'
  pod 'Nimble'
end

target 'P01TapCounter' do

end

target 'P01TapCounterTests' do
  testpods
end

target 'P01TapCounterUITests' do
  testpods
end

